###############################################################################
#
# Makefile for a script - JackAnalyzer project
#
# Students:
# Hanit Hakim, ID 308396480, hanit.hakim@mail.huji.ac.il
#
###############################################################################

all:
	chmod a+x JackAnalyzer
